// <auto-generated />
using System;
using CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EmploiDbContext))]
    partial class EmploiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("emploi")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Domaine.AnnonceEmploi", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DatePublication")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Annonces", "emploi");
                });

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Domaine.Candidature", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnnonceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateDepot")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LettreMotivation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Candidatures", "emploi");
                });

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Domaine.CurriculumVitae", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.PrimitiveCollection<string>("_competences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Competences");

                    b.HasKey("Id");

                    b.ToTable("Cvs", "emploi");
                });

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Domaine.AnnonceEmploi", b =>
                {
                    b.OwnsOne("CVTech.SharedKernel.Domaine.DomaineMetier", "Domaine", b1 =>
                        {
                            b1.Property<Guid>("AnnonceEmploiId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("DomaineCode");

                            b1.Property<string>("Libelle")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("DomaineLibelle");

                            b1.HasKey("AnnonceEmploiId");

                            b1.ToTable("Annonces", "emploi");

                            b1.WithOwner()
                                .HasForeignKey("AnnonceEmploiId");
                        });

                    b.Navigation("Domaine")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
