// <auto-generated />
using System;
using CVTech.Modules.ActualiteEtAbonnement.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVTech.Modules.ActualiteEtAbonnement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ActualiteDbContext))]
    [Migration("20260615145818_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("actualite")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CVTech.Modules.ActualiteEtAbonnement.Domaine.Abonnement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Abonnements", "actualite");
                });

            modelBuilder.Entity("CVTech.Modules.ActualiteEtAbonnement.Domaine.ArticleActualite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuteurId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("DatePublication")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Articles", "actualite");
                });

            modelBuilder.Entity("CVTech.Modules.ActualiteEtAbonnement.Domaine.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTimeOffset>("DateCreation")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinataireId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Lu")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DestinataireId");

                    b.ToTable("Notifications", "actualite");
                });

            modelBuilder.Entity("CVTech.Modules.ActualiteEtAbonnement.Domaine.Abonnement", b =>
                {
                    b.OwnsMany("CVTech.SharedKernel.Domaine.DomaineMetier", "_domaines", b1 =>
                        {
                            b1.Property<Guid>("AbonnementId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Code");

                            b1.Property<string>("Libelle")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("Libelle");

                            b1.HasKey("AbonnementId", "Code");

                            b1.ToTable("AbonnementDomaines", "actualite");

                            b1.WithOwner()
                                .HasForeignKey("AbonnementId");
                        });

                    b.Navigation("_domaines");
                });

            modelBuilder.Entity("CVTech.Modules.ActualiteEtAbonnement.Domaine.ArticleActualite", b =>
                {
                    b.OwnsOne("CVTech.SharedKernel.Domaine.DomaineMetier", "Domaine", b1 =>
                        {
                            b1.Property<Guid>("ArticleActualiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("DomaineCode");

                            b1.Property<string>("Libelle")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("DomaineLibelle");

                            b1.HasKey("ArticleActualiteId");

                            b1.ToTable("Articles", "actualite");

                            b1.WithOwner()
                                .HasForeignKey("ArticleActualiteId");
                        });

                    b.OwnsOne("CVTech.Modules.ActualiteEtAbonnement.Domaine.SourceExterne", "Source", b1 =>
                        {
                            b1.Property<Guid>("ArticleActualiteId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Nom")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("SourceNom");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("SourceUrl");

                            b1.HasKey("ArticleActualiteId");

                            b1.ToTable("Articles", "actualite");

                            b1.WithOwner()
                                .HasForeignKey("ArticleActualiteId");
                        });

                    b.Navigation("Domaine");

                    b.Navigation("Source");
                });
#pragma warning restore 612, 618
        }
    }
}
