// <auto-generated />
using System;
using CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(EmploiDbContext))]
    [Migration("20260626132053_AjoutAgeCv")]
    partial class AjoutAgeCv
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("emploi")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence.Entities.AnnonceEmploiEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DatePublication")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("DomaineCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("DomaineCode");

                    b.Property<string>("DomaineLibelle")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("DomaineLibelle");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TypeContrat")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Annonces", "emploi");
                });

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence.Entities.CandidatureEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnnonceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateDepot")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LettreMotivation")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Candidatures", "emploi");
                });

            modelBuilder.Entity("CVTech.Modules.CatalogueEmploi.Infrastructure.Persistence.Entities.CurriculumVitaeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uniqueidentifier");

                    b.PrimitiveCollection<string>("Competences")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Competences");

                    b.Property<string>("Presentation")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Cvs", "emploi");
                });
#pragma warning restore 612, 618
        }
    }
}
