// <auto-generated />
using System;
using CVTech.Modules.AppelOffreFreelance.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVTech.Modules.AppelOffreFreelance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreelanceDbContext))]
    partial class FreelanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("freelance")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CVTech.Modules.AppelOffreFreelance.Domaine.AppelOffre", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DatePublication")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EntrepriseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PropositionLaureateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("AppelsOffre", "freelance");
                });

            modelBuilder.Entity("CVTech.Modules.AppelOffreFreelance.Domaine.PropositionFreelance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AppelOffreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CandidatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateSoumission")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DureeJours")
                        .HasColumnType("int");

                    b.Property<string>("Methodologie")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("Propositions", "freelance");
                });

            modelBuilder.Entity("CVTech.Modules.AppelOffreFreelance.Domaine.AppelOffre", b =>
                {
                    b.OwnsOne("CVTech.Modules.AppelOffreFreelance.Domaine.CahierDesCharges", "CahierDesCharges", b1 =>
                        {
                            b1.Property<Guid>("AppelOffreId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("BudgetMax")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BudgetMax");

                            b1.Property<decimal>("BudgetMin")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("BudgetMin");

                            b1.Property<string>("Contexte")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("Contexte");

                            b1.Property<DateTimeOffset>("Deadline")
                                .HasColumnType("datetimeoffset")
                                .HasColumnName("Deadline");

                            b1.Property<string>("Livrables")
                                .IsRequired()
                                .HasMaxLength(4000)
                                .HasColumnType("nvarchar(4000)")
                                .HasColumnName("Livrables");

                            b1.HasKey("AppelOffreId");

                            b1.ToTable("AppelsOffre", "freelance");

                            b1.WithOwner()
                                .HasForeignKey("AppelOffreId");
                        });

                    b.OwnsOne("CVTech.SharedKernel.Domaine.DomaineMetier", "Domaine", b1 =>
                        {
                            b1.Property<Guid>("AppelOffreId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("DomaineCode");

                            b1.Property<string>("Libelle")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("nvarchar(120)")
                                .HasColumnName("DomaineLibelle");

                            b1.HasKey("AppelOffreId");

                            b1.ToTable("AppelsOffre", "freelance");

                            b1.WithOwner()
                                .HasForeignKey("AppelOffreId");
                        });

                    b.Navigation("CahierDesCharges")
                        .IsRequired();

                    b.Navigation("Domaine")
                        .IsRequired();
                });

            modelBuilder.Entity("CVTech.Modules.AppelOffreFreelance.Domaine.PropositionFreelance", b =>
                {
                    b.OwnsOne("CVTech.Modules.AppelOffreFreelance.Domaine.BaremeTJM", "Tjm", b1 =>
                        {
                            b1.Property<Guid>("PropositionFreelanceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("MontantJournalier")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Tjm");

                            b1.HasKey("PropositionFreelanceId");

                            b1.ToTable("Propositions", "freelance");

                            b1.WithOwner()
                                .HasForeignKey("PropositionFreelanceId");
                        });

                    b.Navigation("Tjm")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
